#.PHONY:all
#all: hungry  ilder
#
#hungry:Singleton_hungry.cc
#	g++ -o $@ $^ 
#ilder:Singleton_ilder.cc
#	g++ -o $@ $^


hungry:Singleton_hungry.cc
	g++ -o $@ $^

.PHONY:clean
clean:
	rm -f ilder hungry
